spring:
  application:
    name: activity-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    inetutils:
      ignored-interfaces:
        - VirtualBox
        - Hyper-V
        - VMware
      preferred-networks:
        - 127.0.0.1
        - 192.168.
  mongodb:
    database: fitnessactivity
    uri: mongodb://localhost:27017/fitnessactivity

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking